repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.99.5"
    hooks:
      - id: terraform_fmt
        name: format part 6
        files: part-6-cicd
      - id: terraform_docs
        name: terraform-docs part 6
        files: part-6-cicd/src/
        args:
          - --args=--config=part-6-cicd/.terraform-docs.yml
      - id: terraform_fmt
        name: format part 8
        files: part-8-count-condition-for_each/
      - id: terraform_docs
        name: terraform-docs part 6
        files: part-8-count-condition-for_each/src/
        args:
          - --args=--config=part-8-count-condition-for_each/.terraform-docs.yml
